Aprimoramento na busca de discipinas
matrusp/matrusp pull request #60
Opened 2017-12-11 02:40 UTC by Samlibardi

Alterei o algoritmo de busca de disciplinas com base na busca por trigramas ([fonte](https://ii.nlm.nih.gov/MTI/Details/trigram.shtml)) de maneira a:

- encontrar disciplinas por meio de código ou nome aproximado à string pesquisada
- mostrar resultados mais próximos primeiro (ver #39)
- resolver problemas relacionados ao índice da disciplina (e.g. Cálculo I, II, III, IV agora são encontrados corretamente)

_OBS: Um snapshot mostrou o uso de 27MB pela lista de trigramas do banco de dados. Isso equivale a 45% de toda a memória usada pelo matrUSP. Não consegui identificar se esse uso é causado por um leak ou se o algoritmo realmente precisa de tanta memória para funcionar. Vou tentar avaliar melhor._ 

_OBS2: não sabia se aqui era pra escrever em inglês ou não_

2017-12-11 02:51 UTC, pedropaulovc commented
Obrigado pelo pull request! Revisarei nos próximos 2 dias. Primeiro preciso entender como a busca por trigramas funciona.

2017-12-11 16:24 UTC, Samlibardi commented
Acredito que seja possível fazer pequenos ajustes para melhorar a precisão das pesquisas. Estarei submetendo as mudanças que fizer.

2017-12-12 03:45 UTC, pedropaulovc requested changes
No geral as mudanças estão bem encaminhadas. Por favor dê uma olhada nos meus comentários e assim que resolvidos eu farei o deploy no site oficial. Abraços!

2017-12-12 03:45 UTC, pedropaulovc commented on js/database.js
> +	  var lookup = {M:1000,CM:900,D:500,CD:400,C:100,XC:90,L:50,XL:40,X:10,IX:9,V:5,IV:4,I:1},roman = '';
Por favor normalize a indentação. Algumas linhas usam 2 espaços e outras usam tab.

2017-12-12 03:45 UTC, pedropaulovc commented on js/database.js
>  					break;
Este `break` ainda é necessário?

2017-12-12 03:45 UTC, pedropaulovc commented on js/database.js
> +	function trigramsFromString(str) {
Eu apliquei as suas mudanças no [ambiente de homologação](http://bcc.ime.usp.br/matrusp_homolog/) do MatrUSP e fiz alguns testes:

* Disciplinas com numerais arábicos e romanos. Funcionando muito bem.
* "Calc" / "Cálc": Retorna `MNE0614 - Coma` como o primeiro resultado, o que é estranho. Os outros resultados estão condizentes. 
* "MAC": Também retorna `MNE0614 - Coma` como o primeiro resultado, parece que o MatrUSP está assombrado. 😱
* "EAC": Retorna `EFE0148 - Remo` como o segundo resultado, não parece relacionado com os outros resultados.
 
Você poderia verificar a sua implementação por algum *off-by-one error*? No geral os resultados gerados são muito úteis.

2017-12-12 03:45 UTC, pedropaulovc commented on js/database.js
> +				case "DE":
Considere converter esse `switch-case` um array/objeto `stopwords_ptBR`. Daí você pode filtrar `words`. Isso ajuda a legibilidade e internacionalização.

2017-12-12 03:45 UTC, pedropaulovc commented on js/database.js
> +				case "A":
Incluir "para" e "por"?

2017-12-12 03:50 UTC, Samlibardi commented on js/database.js
> +	function trigramsFromString(str) {
Acho que isso deve se dar pela taxação do score baseado no tamanho do nome da disciplina. A função que usei foi ~1/log(tamanho). Vou tentar procurar uma função que não dê tanto valor a disciplinas com 3 ou 4 letras apenas (Cor, Coma, Remo etc)

2017-12-12 05:51 UTC, Samlibardi commented
Fiz algumas alterações na maneira como os trigramas são extraídos das palavras, agora apenas a palavra buscada é tratada como possível sigla, e letras no meio da sigla não são tratadas como letras iniciais. Acredito que o problema das matérias "Coma" e "Remo' esteja resolvido.

2017-12-12 19:08 UTC, Samlibardi commented
Percebi que algumas disciplinas foram colocadas com os algarismos romanos separados por espaço (Ex: Física para engenharia elétrica I I I, pesquisa científica em medicina X V I I I) e algumas tem numeros romanos que não estão no final no nome (Processamento de materiais V I I: Soldagem). Vou fazer alterações para processar esses nomes de forma correta

2017-12-15 04:46 UTC, pedropaulovc commented
Olá Samuel,

Eu não tenho certeza se este PR está relacionado a um comportamento estranho no ambiente de homologação. Eu gostaria que você validasse se você consegue reproduzir:

1. Usando Firefox ou Edge em modo incognito, abra o ambiente de homologação
2. Digite 'a' na caixa de busca de disciplinas
3. Clique no primeiro resultado
4. Digite 'b' na caixa de busca de disciplinas
5. Clique no primeiro resultado
6. Digite 'c' na caixa de busca de disciplinas
7. Clique no primeiro resultado
8. Digite 'c' na caixa de busca de disciplinas
9. Clique no primeiro resultado

Esperado: O MatrUSP deveria listar 4 disciplinas no plano.

Real: Alguns cliques não são registrados. Apenas 2 disciplinas são inseridas no plano.

2017-12-15 14:47 UTC, Samlibardi commented
Olá. Consegui reproduzir no ambiente de homologação. O erro acontece de fato. No entanto, no meu ambiente local o erro não acontece. O ambiente para esse PR contém exatamente o conteúdo mais recente do branch, sem nenhuma outra modificação. Acredito que o erro deve ser causado por outro código presente no ambiente de homologação que não está atualizado para os commits mais recentes.

2017-12-19 02:26 UTC, pedropaulovc approved these changes

2017-12-19 02:27 UTC, pedropaulovc commented
Fiz um redeploy no ambiente de homologação e realmente o problema se foi. :-)

2017-12-19 02:31 UTC, merged