Responsive UI
matrusp/matrusp pull request #61
Opened 2017-12-11 20:30 UTC by Samlibardi

Objetivo: Aumentar a responsividade da UI em telas menores, permitindo a usabilidade do site. Resolver #45 

Alterei o header para utilizar flexbox no arranjo dos itens. O background foi modificado de forma a permitir que a barra aumente verticalmente e mantenha seu design.

2017-12-12 04:24 UTC, pedropaulovc requested changes
Não consegui validar as mudanças no Firefox. Quando este problema for resolvido, eu continuarei com o teste em outros browsers.

2017-12-12 04:24 UTC, pedropaulovc commented on styles/css/application.css
> +html,body,ul,li,header,footer{margin:0;padding:0}ul{list-style:none}li{list-style-type:none}html,body{width:100%;height:100%;min-width:0px;min-height:680px}body{overflow:auto;font-family:tahoma,helve
Apliquei as mudanças no `index.html` e `application.css` no [ambiente de homologação](http://bcc.ime.usp.br/matrusp_homolog/) mas alguma coisa está errada com a renderização no Firefox (58.0b10). O grid de horários não está todo comprimido:

![image](https://user-images.githubusercontent.com/577970/33867331-d7e8916c-deb0-11e7-8692-e790e4f3f23f.png)

Quando este problema for resolvido, eu continuarei com o teste em outros browsers.

2017-12-12 04:28 UTC, pedropaulovc commented on styles/css/application.css
> +html,body,ul,li,header,footer{margin:0;padding:0}ul{list-style:none}li{list-style-type:none}html,body{width:100%;height:100%;min-width:0px;min-height:680px}body{overflow:auto;font-family:tahoma,helve
No Chrome não acontece este problema.

2017-12-12 04:29 UTC, Samlibardi commented on styles/css/application.css
> +html,body,ul,li,header,footer{margin:0;padding:0}ul{list-style:none}li{list-style-type:none}html,body{width:100%;height:100%;min-width:0px;min-height:680px}body{overflow:auto;font-family:tahoma,helve
Interessante. Não havia testado no firefox. Deve ter alguma relação com a altura dos itens dentro da flexbox. Vou tentar resolver e posto o resultado.

2017-12-14 13:59 UTC, Samlibardi commented
Testado e funcionando no firefox 57.0.2

2017-12-15 04:34 UTC, pedropaulovc commented
Olá Samuel, a UI responsiva está ficando muito boa! Eu validei o MatrUSP no Edge, Chrome e Firefox. Alguns comentários finais antes que eu faça o merge do seu PR:

* O menu para carregar e salvar planos está alinhado com a direita da tela ao invés de ficar à esquerda dos botões 

![image](https://user-images.githubusercontent.com/577970/34026914-1876d2d4-e10e-11e7-9489-dc7e12a8f65b.png)

* No Firefox eu não vejo a barra de likes do Facebook. Não estou muito certo por quê. Edge e Chrome estão funcionando bem.

2017-12-15 16:01 UTC, Samlibardi commented
Arrumei a ordem dos elementos do header. A barra de likes aparece corretamente no Firefox:
![2017-12-15](https://user-images.githubusercontent.com/29558451/34049953-592d0982-e1a0-11e7-93ad-689922c5a7bb.png)

2017-12-19 02:23 UTC, pedropaulovc approved these changes

2017-12-19 02:26 UTC, merged